### ISSUE TITLE
Now Deployment Instructions need to change

### ISSUE THREAD

**Issue by joshualinog** [jasonbrandoo/bible-app-react#4]
### Instructions for deployment on now are outdated

Here's the result in the terminal in VS Studio Code:

![image](https://user-images.githubusercontent.com/1839603/76995580-715fd100-6926-11ea-9abe-2c5b663124da.png)

## Now CLI Reference Docs Explain it

> NOTE: The --name option has been deprecated in favor of Project Linking, which allows you to link a ZEIT Now Project to your local codebase when you runnow.

https://zeit.co/docs/now-cli#commands/now/unique-options/name

![image](https://user-images.githubusercontent.com/1839603/76995801-cbf92d00-6926-11ea-8d92-f83ae1f67261.png)

Project linking described here:
https://zeit.co/docs/now-cli#commands/now/project-linking

**Comment by joshualinog** [comment]
@jasonbrandoo , If you want, I'm thinking about changing the instructions in a new branch and just making a pull request that you can merge.

**Comment by jasonbrandoo** [comment]
hey @jajourda I'm sorry lately I'm a little busy, but I have plans to change some code and make documentation better

**Comment by joshualinog** [comment]
### no worries bro
@jasonbrandoo , no worries. Yeshua presently has me in a season of trying to build a webapp that i've been planning to do for years now. (coronavirus 👍 ).

### what kind of changes...?

1. are you going to incorporate typescript?
2. have you thought about using nextjs at all (it makes routing way easier and you can leverage ssr for increasing the speed of the ui experience.) i am also thinking of using your "containers" approach with nextjs to host my own local api route for a version of the bible i have in json format.

**Comment by jasonbrandoo** [comment]
1. nope i think vanilla javascript is enough :smile: 
2. that's a good idea, I think I'm gonna rewrite the app use nextjs in my spare time

thanks for the advice

**Comment by joshualinog** [comment]
sweet. I am trying with to write my project with typescript, i would love to see how you go about incorporating nextjs into this project!

I also saw that you changed the readme :grin:

I'm gonna close this issue. Blessings.
